package spring.transaction.bean;

public class Book {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_book.id
     *
     * @mbg.generated Thu Mar 21 15:19:02 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_book.name
     *
     * @mbg.generated Thu Mar 21 15:19:02 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_book.price
     *
     * @mbg.generated Thu Mar 21 15:19:02 CST 2019
     */
    private Long price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_book.number
     *
     * @mbg.generated Thu Mar 21 15:19:02 CST 2019
     */
    private Integer number;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_book.id
     *
     * @return the value of tbl_book.id
     *
     * @mbg.generated Thu Mar 21 15:19:02 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_book.id
     *
     * @param id the value for tbl_book.id
     *
     * @mbg.generated Thu Mar 21 15:19:02 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_book.name
     *
     * @return the value of tbl_book.name
     *
     * @mbg.generated Thu Mar 21 15:19:02 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_book.name
     *
     * @param name the value for tbl_book.name
     *
     * @mbg.generated Thu Mar 21 15:19:02 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_book.price
     *
     * @return the value of tbl_book.price
     *
     * @mbg.generated Thu Mar 21 15:19:02 CST 2019
     */
    public Long getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_book.price
     *
     * @param price the value for tbl_book.price
     *
     * @mbg.generated Thu Mar 21 15:19:02 CST 2019
     */
    public void setPrice(Long price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_book.number
     *
     * @return the value of tbl_book.number
     *
     * @mbg.generated Thu Mar 21 15:19:02 CST 2019
     */
    public Integer getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_book.number
     *
     * @param number the value for tbl_book.number
     *
     * @mbg.generated Thu Mar 21 15:19:02 CST 2019
     */
    public void setNumber(Integer number) {
        this.number = number;
    }
}