package spring.transaction.dao;

import org.apache.ibatis.annotations.*;
import spring.transaction.bean.Account;
import spring.transaction.bean.AccountExample;

import java.util.List;

public interface AccountMapper {
  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table account
   *
   * @mbg.generated Thu Mar 21 15:19:02 CST 2019
   */
  long countByExample(AccountExample example);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table account
   *
   * @mbg.generated Thu Mar 21 15:19:02 CST 2019
   */
  int deleteByExample(AccountExample example);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table account
   *
   * @mbg.generated Thu Mar 21 15:19:02 CST 2019
   */
  @Delete({
      "delete from account",
      "where id = #{id,jdbcType=INTEGER}"
  })
  int deleteByPrimaryKey(Integer id);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table account
   *
   * @mbg.generated Thu Mar 21 15:19:02 CST 2019
   */
  @Insert({
      "insert into account (id, balance, ",
      "name)",
      "values (#{id,jdbcType=INTEGER}, #{balance,jdbcType=REAL}, ",
      "#{name,jdbcType=VARCHAR})"
  })
  int insert(Account record);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table account
   *
   * @mbg.generated Thu Mar 21 15:19:02 CST 2019
   */
  int insertSelective(Account record);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table account
   *
   * @mbg.generated Thu Mar 21 15:19:02 CST 2019
   */
  List<Account> selectByExample(AccountExample example);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table account
   *
   * @mbg.generated Thu Mar 21 15:19:02 CST 2019
   */
  @Select({
      "select",
      "id, balance, name",
      "from account",
      "where id = #{id,jdbcType=INTEGER}"
  })
  @ResultMap("spring.transaction.dao.AccountMapper.BaseResultMap")
  Account selectByPrimaryKey(Integer id);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table account
   *
   * @mbg.generated Thu Mar 21 15:19:02 CST 2019
   */
  int updateByExampleSelective(@Param("record") Account record, @Param("example") AccountExample example);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table account
   *
   * @mbg.generated Thu Mar 21 15:19:02 CST 2019
   */
  int updateByExample(@Param("record") Account record, @Param("example") AccountExample example);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table account
   *
   * @mbg.generated Thu Mar 21 15:19:02 CST 2019
   */
  int updateByPrimaryKeySelective(Account record);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table account
   *
   * @mbg.generated Thu Mar 21 15:19:02 CST 2019
   */
  @Update({
      "update account",
      "set balance = #{balance,jdbcType=REAL},",
      "name = #{name,jdbcType=VARCHAR}",
      "where id = #{id,jdbcType=INTEGER}"
  })
  int updateByPrimaryKey(Account record);
}