package spring.transaction.dao;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import spring.transaction.bean.Book;
import spring.transaction.bean.BookExample;

import java.util.List;

public interface BookMapper {
  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table tbl_book
   *
   * @mbg.generated Thu Mar 21 15:19:02 CST 2019
   */
  long countByExample(BookExample example);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table tbl_book
   *
   * @mbg.generated Thu Mar 21 15:19:02 CST 2019
   */
  int deleteByExample(BookExample example);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table tbl_book
   *
   * @mbg.generated Thu Mar 21 15:19:02 CST 2019
   */
  @Delete({
      "delete from tbl_book",
      "where id = #{id,jdbcType=INTEGER}"
  })
  int deleteByPrimaryKey(Integer id);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table tbl_book
   *
   * @mbg.generated Thu Mar 21 15:19:02 CST 2019
   */
  @Insert({
      "insert into tbl_book (id, name, ",
      "price, number)",
      "values (#{id,jdbcType=INTEGER}, #{name,jdbcType=VARCHAR}, ",
      "#{price,jdbcType=BIGINT}, #{number,jdbcType=INTEGER})"
  })
  int insert(Book record);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table tbl_book
   *
   * @mbg.generated Thu Mar 21 15:19:02 CST 2019
   */
  int insertSelective(Book record);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table tbl_book
   *
   * @mbg.generated Thu Mar 21 15:19:02 CST 2019
   */
  List<Book> selectByExample(BookExample example);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table tbl_book
   *
   * @mbg.generated Thu Mar 21 15:19:02 CST 2019
   */
  @Select({
      "select",
      "id, name, price, number",
      "from tbl_book",
      "where id = #{id,jdbcType=INTEGER}"
  })
  @ResultMap("spring.transaction.dao.BookMapper.BaseResultMap")
  Book selectByPrimaryKey(Integer id);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table tbl_book
   *
   * @mbg.generated Thu Mar 21 15:19:02 CST 2019
   */
  int updateByExampleSelective(@Param("record") Book record, @Param("example") BookExample example);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table tbl_book
   *
   * @mbg.generated Thu Mar 21 15:19:02 CST 2019
   */
  int updateByExample(@Param("record") Book record, @Param("example") BookExample example);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table tbl_book
   *
   * @mbg.generated Thu Mar 21 15:19:02 CST 2019
   */
  int updateByPrimaryKeySelective(Book record);

  /**
   * This method was generated by MyBatis Generator.
   * This method corresponds to the database table tbl_book
   *
   * @mbg.generated Thu Mar 21 15:19:02 CST 2019
   */
  @Update({
      "update tbl_book",
      "set name = #{name,jdbcType=VARCHAR},",
      "price = #{price,jdbcType=BIGINT},",
      "number = #{number,jdbcType=INTEGER}",
      "where id = #{id,jdbcType=INTEGER}"
  })
  int updateByPrimaryKey(Book record);
}