package edms.mapper;

import edms.model.OmOrder;
import edms.model.OmOrderExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface OmOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table om_order
     *
     * @mbg.generated
     */
    long countByExample(OmOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table om_order
     *
     * @mbg.generated
     */
    int deleteByExample(OmOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table om_order
     *
     * @mbg.generated
     */
    @Delete({
        "delete from om_order",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table om_order
     *
     * @mbg.generated
     */
    @Insert({
        "insert into om_order (id, type, ",
        "confirm_time, total_quantity, ",
        "total_amount, gmt_create, ",
        "gmt_update, is_deleted)",
        "values (#{id,jdbcType=BIGINT}, #{type,jdbcType=TINYINT}, ",
        "#{confirmTime,jdbcType=TIMESTAMP}, #{totalQuantity,jdbcType=INTEGER}, ",
        "#{totalAmount,jdbcType=DECIMAL}, #{gmtCreate,jdbcType=TIMESTAMP}, ",
        "#{gmtUpdate,jdbcType=TIMESTAMP}, #{isDeleted,jdbcType=TINYINT})"
    })
    int insert(OmOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table om_order
     *
     * @mbg.generated
     */
    int insertSelective(OmOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table om_order
     *
     * @mbg.generated
     */
    List<OmOrder> selectByExample(OmOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table om_order
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, type, confirm_time, total_quantity, total_amount, gmt_create, gmt_update, ",
        "is_deleted",
        "from om_order",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @ResultMap("edms.mapper.OmOrderMapper.BaseResultMap")
    OmOrder selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table om_order
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") OmOrder record, @Param("example") OmOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table om_order
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") OmOrder record, @Param("example") OmOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table om_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(OmOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table om_order
     *
     * @mbg.generated
     */
    @Update({
        "update om_order",
        "set type = #{type,jdbcType=TINYINT},",
          "confirm_time = #{confirmTime,jdbcType=TIMESTAMP},",
          "total_quantity = #{totalQuantity,jdbcType=INTEGER},",
          "total_amount = #{totalAmount,jdbcType=DECIMAL},",
          "gmt_create = #{gmtCreate,jdbcType=TIMESTAMP},",
          "gmt_update = #{gmtUpdate,jdbcType=TIMESTAMP},",
          "is_deleted = #{isDeleted,jdbcType=TINYINT}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(OmOrder record);
}