package edms.mapper;

import edms.model.OmOrderItem;
import edms.model.OmOrderItemExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface OmOrderItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table om_order_item
     *
     * @mbg.generated
     */
    long countByExample(OmOrderItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table om_order_item
     *
     * @mbg.generated
     */
    int deleteByExample(OmOrderItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table om_order_item
     *
     * @mbg.generated
     */
    @Delete({
        "delete from om_order_item",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table om_order_item
     *
     * @mbg.generated
     */
    @Insert({
        "insert into om_order_item (id, it, product_id, ",
        "product_price, product_quantity, ",
        "product_unit, product_name, ",
        "product_spec, gmt_create, ",
        "gmt_update, is_deleted)",
        "values (#{id,jdbcType=BIGINT}, #{it,jdbcType=VARCHAR}, #{productId,jdbcType=BIGINT}, ",
        "#{productPrice,jdbcType=DECIMAL}, #{productQuantity,jdbcType=INTEGER}, ",
        "#{productUnit,jdbcType=VARCHAR}, #{productName,jdbcType=VARCHAR}, ",
        "#{productSpec,jdbcType=VARCHAR}, #{gmtCreate,jdbcType=TIMESTAMP}, ",
        "#{gmtUpdate,jdbcType=TIMESTAMP}, #{isDeleted,jdbcType=INTEGER})"
    })
    int insert(OmOrderItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table om_order_item
     *
     * @mbg.generated
     */
    int insertSelective(OmOrderItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table om_order_item
     *
     * @mbg.generated
     */
    List<OmOrderItem> selectByExample(OmOrderItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table om_order_item
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, it, product_id, product_price, product_quantity, product_unit, product_name, ",
        "product_spec, gmt_create, gmt_update, is_deleted",
        "from om_order_item",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @ResultMap("edms.mapper.OmOrderItemMapper.BaseResultMap")
    OmOrderItem selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table om_order_item
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") OmOrderItem record, @Param("example") OmOrderItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table om_order_item
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") OmOrderItem record, @Param("example") OmOrderItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table om_order_item
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(OmOrderItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table om_order_item
     *
     * @mbg.generated
     */
    @Update({
        "update om_order_item",
        "set it = #{it,jdbcType=VARCHAR},",
          "product_id = #{productId,jdbcType=BIGINT},",
          "product_price = #{productPrice,jdbcType=DECIMAL},",
          "product_quantity = #{productQuantity,jdbcType=INTEGER},",
          "product_unit = #{productUnit,jdbcType=VARCHAR},",
          "product_name = #{productName,jdbcType=VARCHAR},",
          "product_spec = #{productSpec,jdbcType=VARCHAR},",
          "gmt_create = #{gmtCreate,jdbcType=TIMESTAMP},",
          "gmt_update = #{gmtUpdate,jdbcType=TIMESTAMP},",
          "is_deleted = #{isDeleted,jdbcType=INTEGER}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(OmOrderItem record);
}