package edms.mapper;

import edms.model.PmProductInfo;
import edms.model.PmProductInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface PmProductInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_product_info
     *
     * @mbg.generated
     */
    long countByExample(PmProductInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_product_info
     *
     * @mbg.generated
     */
    int deleteByExample(PmProductInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_product_info
     *
     * @mbg.generated
     */
    @Delete({
        "delete from pm_product_info",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_product_info
     *
     * @mbg.generated
     */
    @Insert({
        "insert into pm_product_info (id, corp_no, ",
        "brand_no, name, spec, ",
        "price, unit, gmt_create, ",
        "gmt_update, is_deleted, ",
        "images)",
        "values (#{id,jdbcType=BIGINT}, #{corpNo,jdbcType=VARCHAR}, ",
        "#{brandNo,jdbcType=INTEGER}, #{name,jdbcType=VARCHAR}, #{spec,jdbcType=VARCHAR}, ",
        "#{price,jdbcType=DECIMAL}, #{unit,jdbcType=VARCHAR}, #{gmtCreate,jdbcType=TIMESTAMP}, ",
        "#{gmtUpdate,jdbcType=TIMESTAMP}, #{isDeleted,jdbcType=TINYINT}, ",
        "#{images,jdbcType=LONGVARCHAR})"
    })
    int insert(PmProductInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_product_info
     *
     * @mbg.generated
     */
    int insertSelective(PmProductInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_product_info
     *
     * @mbg.generated
     */
    List<PmProductInfo> selectByExampleWithBLOBs(PmProductInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_product_info
     *
     * @mbg.generated
     */
    List<PmProductInfo> selectByExample(PmProductInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_product_info
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, corp_no, brand_no, name, spec, price, unit, gmt_create, gmt_update, is_deleted, ",
        "images",
        "from pm_product_info",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @ResultMap("edms.mapper.PmProductInfoMapper.ResultMapWithBLOBs")
    PmProductInfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_product_info
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") PmProductInfo record, @Param("example") PmProductInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_product_info
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") PmProductInfo record, @Param("example") PmProductInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_product_info
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") PmProductInfo record, @Param("example") PmProductInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_product_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(PmProductInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_product_info
     *
     * @mbg.generated
     */
    @Update({
        "update pm_product_info",
        "set corp_no = #{corpNo,jdbcType=VARCHAR},",
          "brand_no = #{brandNo,jdbcType=INTEGER},",
          "name = #{name,jdbcType=VARCHAR},",
          "spec = #{spec,jdbcType=VARCHAR},",
          "price = #{price,jdbcType=DECIMAL},",
          "unit = #{unit,jdbcType=VARCHAR},",
          "gmt_create = #{gmtCreate,jdbcType=TIMESTAMP},",
          "gmt_update = #{gmtUpdate,jdbcType=TIMESTAMP},",
          "is_deleted = #{isDeleted,jdbcType=TINYINT},",
          "images = #{images,jdbcType=LONGVARCHAR}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKeyWithBLOBs(PmProductInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_product_info
     *
     * @mbg.generated
     */
    @Update({
        "update pm_product_info",
        "set corp_no = #{corpNo,jdbcType=VARCHAR},",
          "brand_no = #{brandNo,jdbcType=INTEGER},",
          "name = #{name,jdbcType=VARCHAR},",
          "spec = #{spec,jdbcType=VARCHAR},",
          "price = #{price,jdbcType=DECIMAL},",
          "unit = #{unit,jdbcType=VARCHAR},",
          "gmt_create = #{gmtCreate,jdbcType=TIMESTAMP},",
          "gmt_update = #{gmtUpdate,jdbcType=TIMESTAMP},",
          "is_deleted = #{isDeleted,jdbcType=TINYINT}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(PmProductInfo record);
}