package edms.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/**
 * 商品信息表
 *
 * @author 李重辰
 * @date   2020/09/02 11:01
 */
public class PmProductInfo implements Serializable {
    /**
     * Database Column Remarks:
     *   使用雪花算法生成分布式唯一ID，不在数据库中自增
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_product_info.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   帐套
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_product_info.corp_no
     *
     * @mbg.generated
     */
    private String corpNo;

    /**
     * Database Column Remarks:
     *   品牌
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_product_info.brand_no
     *
     * @mbg.generated
     */
    private Integer brandNo;

    /**
     * Database Column Remarks:
     *   品名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_product_info.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     * Database Column Remarks:
     *   规格
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_product_info.spec
     *
     * @mbg.generated
     */
    private String spec;

    /**
     * Database Column Remarks:
     *   默认价格
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_product_info.price
     *
     * @mbg.generated
     */
    private BigDecimal price;

    /**
     * Database Column Remarks:
     *   单位
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_product_info.unit
     *
     * @mbg.generated
     */
    private String unit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_product_info.gmt_create
     *
     * @mbg.generated
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_product_info.gmt_update
     *
     * @mbg.generated
     */
    private Date gmtUpdate;

    /**
     * Database Column Remarks:
     *   商品是否被删除
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_product_info.is_deleted
     *
     * @mbg.generated
     */
    private Byte isDeleted;

    /**
     * Database Column Remarks:
     *   商品的详情图片
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pm_product_info.images
     *
     * @mbg.generated
     */
    private String images;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pm_product_info
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_product_info.id
     *
     * @return the value of pm_product_info.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_product_info.id
     *
     * @param id the value for pm_product_info.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_product_info.corp_no
     *
     * @return the value of pm_product_info.corp_no
     *
     * @mbg.generated
     */
    public String getCorpNo() {
        return corpNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_product_info.corp_no
     *
     * @param corpNo the value for pm_product_info.corp_no
     *
     * @mbg.generated
     */
    public void setCorpNo(String corpNo) {
        this.corpNo = corpNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_product_info.brand_no
     *
     * @return the value of pm_product_info.brand_no
     *
     * @mbg.generated
     */
    public Integer getBrandNo() {
        return brandNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_product_info.brand_no
     *
     * @param brandNo the value for pm_product_info.brand_no
     *
     * @mbg.generated
     */
    public void setBrandNo(Integer brandNo) {
        this.brandNo = brandNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_product_info.name
     *
     * @return the value of pm_product_info.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_product_info.name
     *
     * @param name the value for pm_product_info.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_product_info.spec
     *
     * @return the value of pm_product_info.spec
     *
     * @mbg.generated
     */
    public String getSpec() {
        return spec;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_product_info.spec
     *
     * @param spec the value for pm_product_info.spec
     *
     * @mbg.generated
     */
    public void setSpec(String spec) {
        this.spec = spec;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_product_info.price
     *
     * @return the value of pm_product_info.price
     *
     * @mbg.generated
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_product_info.price
     *
     * @param price the value for pm_product_info.price
     *
     * @mbg.generated
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_product_info.unit
     *
     * @return the value of pm_product_info.unit
     *
     * @mbg.generated
     */
    public String getUnit() {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_product_info.unit
     *
     * @param unit the value for pm_product_info.unit
     *
     * @mbg.generated
     */
    public void setUnit(String unit) {
        this.unit = unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_product_info.gmt_create
     *
     * @return the value of pm_product_info.gmt_create
     *
     * @mbg.generated
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_product_info.gmt_create
     *
     * @param gmtCreate the value for pm_product_info.gmt_create
     *
     * @mbg.generated
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_product_info.gmt_update
     *
     * @return the value of pm_product_info.gmt_update
     *
     * @mbg.generated
     */
    public Date getGmtUpdate() {
        return gmtUpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_product_info.gmt_update
     *
     * @param gmtUpdate the value for pm_product_info.gmt_update
     *
     * @mbg.generated
     */
    public void setGmtUpdate(Date gmtUpdate) {
        this.gmtUpdate = gmtUpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_product_info.is_deleted
     *
     * @return the value of pm_product_info.is_deleted
     *
     * @mbg.generated
     */
    public Byte getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_product_info.is_deleted
     *
     * @param isDeleted the value for pm_product_info.is_deleted
     *
     * @mbg.generated
     */
    public void setIsDeleted(Byte isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pm_product_info.images
     *
     * @return the value of pm_product_info.images
     *
     * @mbg.generated
     */
    public String getImages() {
        return images;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pm_product_info.images
     *
     * @param images the value for pm_product_info.images
     *
     * @mbg.generated
     */
    public void setImages(String images) {
        this.images = images;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_product_info
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", corpNo=").append(corpNo);
        sb.append(", brandNo=").append(brandNo);
        sb.append(", name=").append(name);
        sb.append(", spec=").append(spec);
        sb.append(", price=").append(price);
        sb.append(", unit=").append(unit);
        sb.append(", gmtCreate=").append(gmtCreate);
        sb.append(", gmtUpdate=").append(gmtUpdate);
        sb.append(", isDeleted=").append(isDeleted);
        sb.append(", images=").append(images);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_product_info
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        PmProductInfo other = (PmProductInfo) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getCorpNo() == null ? other.getCorpNo() == null : this.getCorpNo().equals(other.getCorpNo()))
            && (this.getBrandNo() == null ? other.getBrandNo() == null : this.getBrandNo().equals(other.getBrandNo()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getSpec() == null ? other.getSpec() == null : this.getSpec().equals(other.getSpec()))
            && (this.getPrice() == null ? other.getPrice() == null : this.getPrice().equals(other.getPrice()))
            && (this.getUnit() == null ? other.getUnit() == null : this.getUnit().equals(other.getUnit()))
            && (this.getGmtCreate() == null ? other.getGmtCreate() == null : this.getGmtCreate().equals(other.getGmtCreate()))
            && (this.getGmtUpdate() == null ? other.getGmtUpdate() == null : this.getGmtUpdate().equals(other.getGmtUpdate()))
            && (this.getIsDeleted() == null ? other.getIsDeleted() == null : this.getIsDeleted().equals(other.getIsDeleted()))
            && (this.getImages() == null ? other.getImages() == null : this.getImages().equals(other.getImages()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pm_product_info
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getCorpNo() == null) ? 0 : getCorpNo().hashCode());
        result = prime * result + ((getBrandNo() == null) ? 0 : getBrandNo().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getSpec() == null) ? 0 : getSpec().hashCode());
        result = prime * result + ((getPrice() == null) ? 0 : getPrice().hashCode());
        result = prime * result + ((getUnit() == null) ? 0 : getUnit().hashCode());
        result = prime * result + ((getGmtCreate() == null) ? 0 : getGmtCreate().hashCode());
        result = prime * result + ((getGmtUpdate() == null) ? 0 : getGmtUpdate().hashCode());
        result = prime * result + ((getIsDeleted() == null) ? 0 : getIsDeleted().hashCode());
        result = prime * result + ((getImages() == null) ? 0 : getImages().hashCode());
        return result;
    }
}